### ISSUE TITLE
Vague error message if game wasn't launched at least once previously

### ISSUE THREAD

**Issue by C0rn3j** [NaokiStark/Crewmate-switcher#2]
Using the 1.1 release, I can't get it to work on LineageOS 17.1, which is based on Android 10.

Also, would you consider uploading it to F-Droid?

<img src="https://user-images.githubusercontent.com/1641362/97051095-df383f00-157e-11eb-9c61-89d6dd17aa4b.png" width="100" height="200">

**Comment by Nekitaw** [comment]
I don't have a phone that runs android 10, and android emu only works in x86 (Among Us only works on ARM)
'll try debug with raspberry

**Comment by tuxinal** [comment]
i have tested with an android 10 device(not specifically lineage os) and it works fine could you provide a logcat?

**Comment by C0rn3j** [comment]
```
10-27 21:54:00.305  8506  8506 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.innersloth.spacemafia/files/regionInfo.dat: open failed: ENOENT (No such file or directory)
```
This happens if you never opened the game before, which I did not (smart, huh?)

Maybe add a verbose error message - If `/storage/emulated/0/Android/data/com.innersloth.spacemafia` does not exist, throw an error that the game needs to be launched at least once.

**Comment by Nekitaw** [comment]
It's not an specific app error.

**Comment by C0rn3j** [comment]
Having to launch the game once is not written anywhere as a requirement, so the error message is useless.

I agree that vast majority of people trying this will already have launched it once before, but for those that didn't and are just testing if the app works this is mighty confusing.

**Comment by tuxinal** [comment]
It's a thing that is expected from the user shouldn't be specified really. Maybe in the readme?

**Comment by Nekitaw** [comment]
https://github.com/NaokiStark/Crewmate-switcher/commit/05f6714982186b10cf7eb51471dce69eed1dacaa

**Comment by Nekitaw** [comment]
https://github.com/NaokiStark/Crewmate-switcher/commit/3feb0f78a10b9b3f6669f889df33806ee9efaa5a works

https://www.youtube.com/watch?v=__t400HKw8Y
